# Generated by Django 5.1.15 on 2026-06-23 11:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auto_send_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auto_send_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_format',
            field=models.CharField(choices=[('PLAIN', 'Plain text'), ('SLACK', 'Slack'), ('EMAIL', 'Manager email')], default='PLAIN', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_length',
            field=models.CharField(choices=[('brief', 'Brief'), ('standard', 'Standard'), ('detailed', 'Detailed')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_tone',
            field=models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual'), ('concise', 'Concise')], default='professional', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_auto_send_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quiet_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quiet_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.CreateModel(
            name='EODReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('format', models.CharField(choices=[('PLAIN', 'Plain text'), ('SLACK', 'Slack'), ('EMAIL', 'Manager email')], default='PLAIN', max_length=10)),
                ('tone', models.CharField(default='professional', max_length=20)),
                ('length', models.CharField(default='standard', max_length=20)),
                ('content', models.TextField()),
                ('auto_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eod_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='myApp_eodre_user_id_c320b0_idx'), models.Index(fields=['user', '-created_at'], name='myApp_eodre_user_id_099438_idx')],
            },
        ),
    ]
