# Generated by Django 5.1.15 on 2026-06-23 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def drop_legacy_department_text(apps, schema_editor):
    """Clear free-text department values before FK conversion (pilot re-assign in admin)."""
    UserProfile = apps.get_model("myApp", "UserProfile")
    UserProfile.objects.all().update(department="")


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0002_userprofile_auto_send_enabled_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="eodreport",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("SUBMITTED", "Submitted")],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="eodreport",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("EMPLOYEE", "Employee"), ("MANAGER", "Manager"), ("BOSS", "Boss")],
                default="EMPLOYEE",
                max_length=20,
            ),
        ),
        migrations.RunPython(drop_legacy_department_text, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="userprofile",
            name="department",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="myApp.department",
            ),
        ),
        migrations.AddIndex(
            model_name="eodreport",
            index=models.Index(fields=["status", "date"], name="myApp_eodre_status_09c8ba_idx"),
        ),
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("department__isnull", False), ("role", "MANAGER")),
                fields=("department",),
                name="unique_manager_per_department",
            ),
        ),
    ]
