# Generated by Django 5.1.15 on 2026-06-23 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_org_structure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eodreport',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_eod_per_user_per_day'),
        ),
    ]
