# Generated by Django 5.1.15 on 2026-06-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_task_assigned_by_notifications'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tasknotification',
            new_name='myApp_taskn_recipie_2bcece_idx',
            old_name='myApp_taskn_recipie_idx',
        ),
    ]
