# Generated by Django 5.1.15 on 2026-06-29 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_eod_archive_draft'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eodreportarchive',
            new_name='myApp_eodre_user_id_0836d5_idx',
            old_name='myapp_eodar_user_id_sub_idx',
        ),
        migrations.RenameIndex(
            model_name='eodreportarchive',
            new_name='myApp_eodre_user_id_ff534c_idx',
            old_name='myapp_eodar_user_id_log_idx',
        ),
    ]
