# Generated by Django 5.1.15 on 2026-07-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_eodreport_project_progress'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userprojectprogress',
            new_name='myApp_userp_user_id_7954b3_idx',
            old_name='myapp_userpr_user_id_6f0a0a_idx',
        ),
    ]
