from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("history/", views.eod_history_page, name="eod_history"),
    path("login/", views.login_view, name="login"),
    path("oversight/login/", views.oversight_login_view, name="oversight_login"),
    path("logout/", views.logout_view, name="logout"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("api/profile/", views.api_profile, name="api_profile"),
    path("api/profile/update/", views.api_profile_update, name="api_profile_update"),
    path("api/users/", views.api_users, name="api_users"),
    path("api/tasks/", views.api_tasks, name="api_tasks"),
    path("api/tasks/clear/", views.api_tasks_clear, name="api_tasks_clear"),
    path("api/tasks/bulk/", views.api_tasks_bulk, name="api_tasks_bulk"),
    path("api/tasks/<int:task_id>/", views.api_task_detail, name="api_task_detail"),
    path("api/tasks/<int:task_id>/blocker/", views.api_task_blocker, name="api_task_blocker"),
    path("api/tasks/<int:task_id>/mark-blocked/", views.api_task_mark_blocked, name="api_task_mark_blocked"),
    path("braindump/", views.braindump, name="braindump"),
    path("api/generate-eod/", views.generate_eod_report_view, name="generate_eod_report"),
    path("api/eod/submit/", views.api_eod_submit, name="api_eod_submit"),
    path("api/oversight/assistant/summary/", views.api_oversight_assistant_summary, name="api_oversight_assistant_summary"),
    path("api/oversight/assistant/chat/", views.api_oversight_assistant_chat, name="api_oversight_assistant_chat"),
    path("api/oversight/assign-task/", views.api_oversight_assign_task, name="api_oversight_assign_task"),
    path("api/notifications/", views.api_notifications, name="api_notifications"),
    path("api/notifications/read/", views.api_notifications_read, name="api_notifications_read"),
    path("api/insights/consistency/", views.api_insights_consistency, name="api_insights_consistency"),
    path("api/insights/wins/", views.api_insights_wins, name="api_insights_wins"),
    path("api/week-review/", views.api_week_review, name="api_week_review"),
    path("api/search/", views.api_search, name="api_search"),
    path("api/reports/", views.api_reports_history, name="api_reports_history"),
    path("api/reports/<int:report_id>/", views.api_report_detail, name="api_report_detail"),
]
